#!/bin/bash

. /etc/os-release

send_notification() {
	prio="${1}"
	subject="${2}"
	body="${3}"

	if ! which notify-send &>/dev/null; then
		echo "E: notify-send not found, unable to send upgrade complete notification" >&2
		return 1
	fi

	notify-send \
		-a "${NAME}" \
		-i emblem-droidian \
		-u "${prio}" \
		"${subject}" \
		"${body}"
}

# Wait a bit to catch the user's attention
sleep 10

send_notification normal "System update completed" "You successfully updated to ${PRETTY_NAME}."

# We don't really care if the notification went out or not
exit 0
